version: '3.7'
services:
  fe:
    image: untadee/comment-survey-fe:latest
    networks:
      - traefik-public
    depends_on:
      - be
    deploy:
      # service resource management
      # resources:
        # Hard limit - Docker does not allow to allocate more
        # limits:
        #   cpus: '0.50'
        #   memory: 512M
        # Soft limit - Docker makes best effort to return to it
        # reservations:
        #   cpus: '0.50'
        #   memory: 256M
      # service restart policy
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.comment-survey-fe.rule=Host(`rais.dista.uninsubria.it`)
        - traefik.http.routers.comment-survey-fe.entrypoints=https
        - traefik.http.routers.comment-survey-fe.tls=true
        - traefik.http.services.comment-survey-fe.loadbalancer.server.port=3000
  be:
    image: untadee/comment-survey-be:latest
    networks:
      - mongodb_net
    environment:
      - MONGODB_URL=mongodb://admin:123123@mongodb_container:27017/comment-survey?authSource=admin
    deploy:
      labels:
        # Frontend
        - "traefik.enable=true"
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.comment-survey-be.rule=Host(`rais.dista.uninsubria.it`) && PathPrefix(`/comment-api/`)"
        - "traefik.http.routers.comment-survey-be.entrypoints=https"
        - traefik.http.routers.comment-survey-be.tls=true
        - "traefik.http.services.comment-survey-be.loadbalancer.server.port=3333"

networks:
  traefik-public:
    external: true
  mongodb_net:
    external: true
volumes:
  data:


