version: '3.7'
services:
  fe:
    image: untadee/comment-survey-fe-2:latest
    networks:
      - traefik-public
    deploy:
      # service resource management
      # resources:
        # Hard limit - Docker does not allow to allocate more
        # limits:
        #   cpus: '0.50'
        #   memory: 512M
        # Soft limit - Docker makes best effort to return to it
        # reservations:
        #   cpus: '0.50'
        #   memory: 256M
      # service restart policy
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.comment-survey-fe-2.rule=Host(`rais2.dista.uninsubria.it`)
        - traefik.http.routers.comment-survey-fe-2.entrypoints=http
        - traefik.http.routers.comment-survey-fe-2.middlewares=https-redirect
        - traefik.http.routers.comment-survey-fe-2.entrypoints=https
        - traefik.http.routers.comment-survey-fe-2.tls=true
        - traefik.http.services.comment-survey-fe-2.loadbalancer.server.port=3000

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

        - traefik.http.routers.comment-survey-fe-2.tls.certresolver=le
networks:
  traefik-public:
    external: true
  mongodb_net:
    external: true
volumes:
  data:


